### ISSUE TITLE
Android AudioConfig.fromWavFileInput : Cannot read properties of undefined (reading 'slice')

### ISSUE THREAD

**Issue by nwabdou85** [glharper/cognitive-js-sdk-react-native#2]
Hi @glharper ;

Based on code, I was trying to transcribe a local wav file (put in the app inside raw folder); 

I get this error , when try to configure audio `AudioConfig.fromWavFileInput("apprendre.wav")`

This is the error

`YellowBox.js:71 Possible Unhandled Promise Rejection (id: 0):
TypeError: Cannot read properties of undefined (reading 'slice')
TypeError: Cannot read properties of undefined (reading 'slice')
    at FileAudioSource.readHeader (blob:http://localhost:8081/a0662c65-0150-4a96-9b83-7398e671849a:256971:32)
    at new FileAudioSource (blob:http://localhost:8081/a0662c65-0150-4a96-9b83-7398e671849a:256877:42)
    at Function.AudioConfig.fromWavFileInput (blob:http://localhost:8081/a0662c65-0150-4a96-9b83-7398e671849a:271177:34)
    at getRecognizer$ (blob:http://localhost:8081/a0662c65-0150-4a96-9b83-7398e671849a:230788:51)
    at tryCatch (blob:http://localhost:8081/a0662c65-0150-4a96-9b83-7398e671849a:48040:19)
    at Generator.invoke [as _invoke] (blob:http://localhost:8081/a0662c65-0150-4a96-9b83-7398e671849a:48210:24)
    at Generator.next (blob:http://localhost:8081/a0662c65-0150-4a96-9b83-7398e671849a:48082:23)
    at tryCatch (blob:http://localhost:8081/a0662c65-0150-4a96-9b83-7398e671849a:48040:19)
    at invoke (blob:http://localhost:8081/a0662c65-0150-4a96-9b83-7398e671849a:48112:22)
    at blob:http://localhost:8081/a0662c65-0150-4a96-9b83-7398e671849a:48142:13`

and when I give it a buffer object , I got this error:

`YellowBox.js:71 Possible Unhandled Promise Rejection (id: 0):
Error: ENOENT: : open failed: ENOENT (No such file or directory), open 'apprendre.wav'
Error: ENOENT: : open failed: ENOENT (No such file or directory), open 'apprendre.wav'
    at createErrorFromErrorData (blob:http://localhost:8081/6b5043d4-2623-48c2-a138-adc26c016f82:21669:17)
    at blob:http://localhost:8081/6b5043d4-2623-48c2-a138-adc26c016f82:21628:27
    at MessageQueue.__invokeCallback (blob:http://localhost:8081/6b5043d4-2623-48c2-a138-adc26c016f82:22533:18)
    at blob:http://localhost:8081/6b5043d4-2623-48c2-a138-adc26c016f82:22259:18
    at MessageQueue.__guard (blob:http://localhost:8081/6b5043d4-2623-48c2-a138-adc26c016f82:22447:13)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (blob:http://localhost:8081/6b5043d4-2623-48c2-a138-adc26c016f82:22258:14)
    at http://localhost:8081/debugger-ui/debuggerWorker.js:80:58`

Any help here, please ?

**Comment by nwabdou85** [comment]
@glharper any help here, please ?

**Comment by glharper** [comment]
@nwabdou85 Could you attach the wav file you're using to reproduce this?

**Comment by nwabdou85** [comment]
For sure , here the link https://file.io/WL7KOpxmzzn9 of the file, I couldn't attach it here

**Comment by glharper** [comment]
@nwabdou85  A couple of random thoughts...this is an ALAW file with a 60-byte long header. Does this reproduce with files that have 44 byte header? Also, what happens when you update the dependency on microsoft-cognitiveservices-speech-sdk to 1.20.0 or 1.21.0?

**Comment by nwabdou85** [comment]
![IMG_20220421_003241](https://user-images.githubusercontent.com/6404998/164341691-e1c7ee15-9bfb-43d9-94be-1a53c6de4a8e.jpg)

That what I get actually with microsoft-cognitiveservices-speech-sdk to 1.20.0 

> const getBufferFromUri = async(uri, name) => {

     const NewFilePath = await getPath(uri);
    console.log('NewFilePath',NewFilePath);
    const utf8string = await RNFS.readFile(NewFilePath, 'base64');
    return Buffer.from(utf8string, 'base64');
}



> export const getPath = async(uri: string) => {
  console.log('656 uri',uri);
  if (uri.startsWith('content://')) {
     let uriresult = await RNFetchBlob.fs.stat(uri)
           .then(info => console.log('info',info))
           .catch((err) => console.log('stat err',err));
    console.log('uriresult', uriresult);
    return uriresult;
  }
  return `file://${uri}`;
};

**Comment by nwabdou85** [comment]
@glharper please need your advice and suggestion to do an azure  speech to text feature with react native; here the process 
 

- The device asks for permission to use the microphone -> this is ok

- The doctor use a package to record an audio file of the user’s speech(the package don't defined yet). --> not yet

- The audio file is sent to Azure Speech API, with the speciality of the doctor.--> not yet

- The API use the model of each speciality to translate --> not yet

- The Speech API returns a text translation of the audio. --> not yet

- The doctor verify the text, and correct if necessary --> not yet

- The audio file is deleted, if no correction; --> not yet

- If the doctor correct the text, Sent the audio file with the text to API to train the model.

- This text is fed into the Mongo db.


I tried to use your package, but I still have problems and I'am waiting a lot of time to do it :( 

Thanks you for your help

**Comment by glharper** [comment]
@nwabdou85 Looking at the debug output, and your code:
- you get a uri with content there correctly
- RNFetchBlob.fs.stat(uri) throws an error

Is RNFetchBlob a Speech SDK class? I don't think this is an error I can make suggestions for, other than googling "failed to stat path 'null'" for content:// files.

**Comment by nwabdou85** [comment]
@glharper  Thank's you for your time; 
Any guid or suggestion for this  [comment](https://github.com/glharper/cognitive-js-sdk-react-native/issues/2#issuecomment-1114200839) ?

**Comment by glharper** [comment]
The audio file is sent to Azure Speech API, with the speciality of the doctor.--> This can be done with TranslationRecognizer, using the same audio config as this sample, but with the TranslationRecognizer class, as used [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/2cc99fc90f77930e458623cae43bf28022029ea5/samples/js/browser/index.html#L865)

The API use the model of each speciality to translate --> If you have a custom translation model with an endpoint id, you can set the endpoint id on the SpeechConfig object and get results from that specific model. 

The Speech API returns a text translation of the audio. --> You can attach a callback to the translationRecognizer.recognized event. See [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/2cc99fc90f77930e458623cae43bf28022029ea5/samples/js/browser/index.html#L592) for an example handling that callback.

The other steps you listed are out of scope for the capabilities of Speech SDK.
